# Generated by Django 4.2.30 on 2026-10-02 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '매장',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LotterySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('registration_token', models.CharField(blank=True, default='', max_length=64)),
                ('max_per_phone', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_settings', to='lottery_app.store')),
            ],
            options={
                'verbose_name': '추첨 설정',
            },
        ),
        migrations.CreateModel(
            name='LotteryApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('has_children', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_winner', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='lottery_app.store')),
            ],
            options={
                'verbose_name': '응모자',
                'ordering': ['store', 'entry_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotteryapplicant',
            constraint=models.UniqueConstraint(fields=('store', 'entry_no'), name='uniq_store_entry_no'),
        ),
    ]
