# Generated by Django 4.2.30 on 2026-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryapplicant',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotteryapplicant',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
