# Generated by Django 4.2.30 on 2026-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0002_lotteryapplicant_children_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryapplicant',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
