# Generated by Django 4.2.30 on 2026-10-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0003_lotteryapplicant_picked_up_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', '등록'), ('cancel', '취소'), ('reset', '추첨종료·삭제')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('entry_no', models.IntegerField(blank=True, null=True)),
                ('children_count', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='lottery_app.store')),
            ],
            options={
                'verbose_name': '감사 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
