# Generated by Django 4.2.30 on 2026-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('called', '호출완료')], default='waiting', max_length=10)),
                ('push_subscription', models.JSONField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '고객',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='QueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '대기 설정',
            },
        ),
    ]
