# Generated by Django 4.2.30 on 2026-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesettings',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='registration_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
