# Generated by Django 4.2.30 on 2026-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_customer_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesettings',
            name='gps_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
