# Generated by Django 4.2.30 on 2026-05-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0004_queuesettings_gps_enabled_queuesettings_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuesettings',
            name='gps_enabled',
        ),
        migrations.RemoveField(
            model_name='queuesettings',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='queuesettings',
            name='longitude',
        ),
    ]
